import * as styled from "styled-components";

/*
Color generated by https://coolors.co/0d3b66-faf0ca-f4d35e-ee964b-f95738
*/
export default styled.createGlobalStyle`
  :root {
    --indigo-dye: hsla(209, 77%, 23%, 1);
    --lemon-meringue: hsla(48, 83%, 89%, 1);
    --orange-yellow-crayola: hsla(47, 87%, 66%, 1);
    --sandy-brown: hsla(28, 83%, 61%, 1);
    --orange-soda: hsla(10, 94%, 60%, 1);
    --green-blue-crayola: hsla(209, 52%, 51%, 1);
    --black-chocolate: hsla(39, 52%, 6%, 1);
    --black-coffee: hsla(20, 14%, 17%, 1);
    --red-orange-color-wheel: hsla(16, 97%, 53%, 1);
    --old-lace: hsla(48, 56%, 93%, 1);
  }
  body {
    margin: 0;
    font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", "Roboto",
      "Oxygen", "Ubuntu", "Cantarell", "Fira Sans", "Droid Sans",
      "Helvetica Neue", sans-serif;
    -webkit-font-smoothing: antialiased;
    -moz-osx-font-smoothing: grayscale;
    background-color:var(--old-lace);
  }
  code {
    font-family: source-code-pro, Menlo, Monaco, Consolas, "Courier New",
      monospace;
  }
  .gb-color-primary{
    color:var(--green-blue-crayola)
    
  }
  .gb-text-main{
    color:var(--black-chocolate)
  }
  .gb-text-append{
    color:var(--black-chocolate)
  }
`;
